/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coverick.aoc

import coverick.aoc.day1.calorieCountingSolution

fun main() {
    println("Calorie Counting Solution: ${calorieCountingSolution()}")
    
}
